In [1]:
from sklearn.model_selection import StratifiedKFold

In [4]:
import numpy as np

In [5]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [6]:
skf = StratifiedKFold( n_splits=3)
skf.get_n_splits(x, y)

3

In [7]:
for i, (train_index, test_index) in enumerate( skf.split(x, y) ):
 print(f"Fold {i}:")
 print(f" Train: index={train_index}")
 print(f" Test: index={test_index}")

Fold 0:
 Train: index=[ 4  5  6  7  8  9 10 11]
 Test: index=[0 1 2 3]
Fold 1:
 Train: index=[ 0  1  2  3  8  9 10 11]
 Test: index=[4 5 6 7]
Fold 2:
 Train: index=[0 1 2 3 4 5 6 7]
 Test: index=[ 8  9 10 11]


In [8]:
for i, (train_index, test_index) in enumerate( skf.split(x, y) ):
 print('\n\n Fold', i)
 print(' Train data')
 print(' x_train\n', x[train_index])
 print(' y_train:', y[train_index])
 print(' Test data', x[test_index])
 print(' x_test\n', x[test_index])
 print(' y_test:', y[test_index])



 Fold 0
 Train data
 x_train
 [[ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
 y_train: [1 0 0 1 1 0 1 0]
 Test data [[1 2]
 [3 4]
 [5 6]
 [7 8]]
 x_test
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
 y_test: [0 1 1 0]


 Fold 1
 Train data
 x_train
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
 y_train: [0 1 1 0 1 0 1 0]
 Test data [[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
 x_test
 [[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
 y_test: [1 0 0 1]


 Fold 2
 Train data
 x_train
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
 y_train: [0 1 1 0 1 0 0 1]
 Test data [[17 18]
 [19 20]
 [21 22]
 [23 24]]
 x_test
 [[17 18]
 [19 20]
 [21 22]
 [23 24]]
 y_test: [1 0 1 0]


In [10]:
from sklearn.metrics import accuracy_score

In [20]:
n_class = len(np.unique(y))
print(n_class)

2


In [24]:
for i, (train_index, test_index) in enumerate(skf.split(x, y)):
 print('\n\n Fold', i)
 x_train, y_train = x[train_index], y[train_index]
 x_test, y_test = x[test_index], y[test_index]

 # Training accuracy
 y_true = y_train
 y_pred = np.random.randint(n_class, size=y_train.shape[0])
 acc = accuracy_score(y_true, y_pred); print('training accuracy:', acc)

 # Testing accuracy
 y_true = y_test
 y_pred = np.random.randint(n_class, size=y_test.shape[0])
 acc = accuracy_score(y_true, y_pred); print('testing accuracy:', acc)



 Fold 0
training accuracy: 0.25
testing accuracy: 0.75


 Fold 1
training accuracy: 0.625
testing accuracy: 0.5


 Fold 2
training accuracy: 0.375
testing accuracy: 0.0


In [25]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [26]:
# Load IRIS DATA
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
print(X); print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [27]:
# Data description
print(X.shape)
print(np.unique(y))
n_class = len(np.unique(y))

(150, 4)
[0 1 2]


In [28]:
# Fit model
clf = LogisticRegression(random_state=0).fit(X, y)

C:\Users\DELL\anaconda3\envs\main\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
# Making prediction
x_test = X[5:9, :]; print(x_test)
clf.predict(x_test)

[[5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]]


array([0, 0, 0, 0])

In [31]:
# Checking predicted probability output
clf.predict_proba( x_test)


array([[9.70472207e-01, 2.95277198e-02, 7.35204121e-08],
       [9.86891614e-01, 1.31083659e-02, 1.99835378e-08],
       [9.76411331e-01, 2.35886416e-02, 2.76274920e-08],
       [9.79851464e-01, 2.01485057e-02, 3.06923827e-08]])

In [32]:
# Evaluation
clf.score(X, y)

0.9733333333333334

In [39]:
# Evaluation
y_test = y[5:9]
clf.score(x_test, y_test)

1.0

In [117]:
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import train_test_split

In [56]:
# Loading data
data = load_iris()

In [57]:
# Splitting the independent and dependent variables
X = data.data
Y = data.target

In [58]:
# Data description
print(X.shape)
print(np.unique(y))
n_class = len(np.unique(y))

(150, 4)
[0 1 2]


In [62]:
# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,
random_state = 99)

In [63]:
# Fit model
clf = LogisticRegression(random_state=0).fit(X_train, Y_train)
clf.predict(X_test) # Making prediction
clf.predict_proba(X_test) # Checking predicted probability output

array([[9.05265273e-05, 1.08253757e-01, 8.91655717e-01],
       [9.72152423e-01, 2.78473839e-02, 1.93206478e-07],
       [1.11715288e-02, 9.12671498e-01, 7.61569736e-02],
       [1.57355957e-05, 3.34579924e-02, 9.66526272e-01],
       [9.81448227e-01, 1.85516873e-02, 8.57510600e-08],
       [2.52191778e-02, 9.18300453e-01, 5.64803695e-02],
       [7.84705839e-03, 7.78861836e-01, 2.13291106e-01],
       [1.46301282e-05, 6.90762077e-02, 9.30909162e-01],
       [9.42106451e-01, 5.78924448e-02, 1.10464403e-06],
       [3.37316800e-03, 4.46128312e-01, 5.50498520e-01],
       [1.44981502e-07, 7.13668743e-03, 9.92863168e-01],
       [4.53423790e-03, 8.82283114e-01, 1.13182648e-01],
       [1.63673440e-03, 3.94336263e-01, 6.04027003e-01],
       [1.89320306e-02, 8.96309311e-01, 8.47586582e-02],
       [3.27129939e-05, 5.09728991e-02, 9.48994388e-01],
       [9.85416032e-01, 1.45839003e-02, 6.80874266e-08],
       [9.62492305e-01, 3.75074917e-02, 2.02869283e-07],
       [2.40103822e-02, 9.34251

In [64]:
# Evaluation
tr_acc =clf.score(X_train, Y_train); print('training accuracy: ', tr_acc)
te_acc = clf.score(X_test, Y_test); print('testing accuracy: ', te_acc)

training accuracy:  0.9809523809523809
testing accuracy:  0.9555555555555556


In [65]:
import pandas as pd

In [139]:
df_path = 'heart_disease.csv'
data = pd.read_csv(df_path)
data.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [140]:
# Data description
print(data.shape)
print(data.nunique())

(4238, 16)
male                  2
age                  39
education             4
currentSmoker         2
cigsPerDay           33
BPMeds                2
prevalentStroke       2
prevalentHyp          2
diabetes              2
totChol             248
sysBP               234
diaBP               146
BMI                1363
heartRate            73
glucose             143
TenYearCHD            2
dtype: int64


In [141]:
# Data description
print(data.shape)
print(data.nunique())
n_class = len(np.unique(data['TenYearCHD'])) ; print(n_class)

(4238, 16)
male                  2
age                  39
education             4
currentSmoker         2
cigsPerDay           33
BPMeds                2
prevalentStroke       2
prevalentHyp          2
diabetes              2
totChol             248
sysBP               234
diaBP               146
BMI                1363
heartRate            73
glucose             143
TenYearCHD            2
dtype: int64
2


In [142]:
xx = data.iloc[:,0:-1]
Y = data['TenYearCHD']
#yy = np.array(Y)

In [143]:
# Splitting data
X_train, X_test, Y_train, Y_test = train_test_split(xx, yy, test_size=0.3,
random_state = 0)

In [144]:
# Fit model
clf = LogisticRegression(random_state=0).fit(X_train, Y_train)
clf.predict(X_test) # Making prediction
clf.predict_proba(X_test) # Checking predicted probability output

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [138]:
# Evaluation
tr_acc =clf.score(X_train, Y_train); print('training accuracy: ', tr_acc)
te_acc = clf.score(X_test, Y_test); print('testing accuracy: ', te_acc)

C:\Users\DELL\anaconda3\envs\main\lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values