In [1]:
import pandas as pd

In [2]:
df_path = 'heart_disease.csv'
df = pd.read_csv(df_path)
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
df.nunique()

male                  2
age                  39
education             4
currentSmoker         2
cigsPerDay           33
BPMeds                2
prevalentStroke       2
prevalentHyp          2
diabetes              2
totChol             248
sysBP               234
diaBP               146
BMI                1363
heartRate            73
glucose             143
TenYearCHD            2
dtype: int64

In [4]:
hot = pd.get_dummies(df['education'])

In [5]:
hot

1.0  2.0  3.0  4.0
0       0    0    0    1
1       0    1    0    0
2       1    0    0    0
3       0    0    1    0
4       0    0    1    0
...   ...  ...  ...  ...
4233    1    0    0    0
4234    0    0    1    0
4235    0    1    0    0
4236    1    0    0    0
4237    0    1    0    0

[4238 rows x 4 columns]

In [6]:
df = pd.concat([df, hot], axis = 1)
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  1.0  2.0  3.0  4.0  
0           0    0    0    0    1  
1           0    0    1    0    0  
2           0    1    0    0    0  
3           1    0    0    1    0  
4           0    0    0    1    0

In [9]:
df = df.drop(['education'], axis = 1)
df.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  1.0  2.0  3.0  4.0  
0           0    0    0    0    1  
1           0    0    1    0    0  
2           0    1    0    0    0  
3           1    0    0    1    0  
4           0    0    0    1    0

In [11]:
import sklearn as sk

In [12]:
import numpy as np

In [13]:
from sklearn.model_selection import train_test_split

In [17]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [18]:
np.unique(y)

array([0, 1])

In [19]:
n_class = len(np.unique(y))
print(n_class)

2


In [20]:
print(x); print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[0 1 1 0 1 0 0 1 1 0 1 0]


In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
print('y_train\n',y_train)
print('train_size:', y_train.shape)
print('y_test\n',y_test)
print('test_size:', y_test.shape)

y_train
 [1 0 1 0 0 1 0 1 1]
train_size: (9,)
y_test
 [0 1 0]
test_size: (3,)


In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)
print('y_train\n',y_train)
print('train_size:', y_train.shape)
print('y_test\n',y_test)
print('test_size:', y_test.shape)

y_train
 [1 0 1 0 0 1 1 1]
train_size: (8,)
y_test
 [0 0 1 0]
test_size: (4,)


In [33]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 4)
print('y_train\n',y_train)
print('train_size:', y_train.shape)
print('y_test\n',y_test)
print('test_size:', y_test.shape)

y_train
 [1 1 0 0 1 0 1 1]
train_size: (8,)
y_test
 [0 1 0 0]
test_size: (4,)


In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 4, stratify = y)
print('y_train\n',y_train)
print('train_size:', y_train.shape)
print('y_test\n',y_test)
print('test_size:', y_test.shape)

y_train
 [1 0 1 0 1 0 0 1]
train_size: (8,)
y_test
 [0 0 1 1]
test_size: (4,)


In [35]:
from sklearn.metrics import accuracy_score

In [36]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.33, random_state = 4, stratify = y)

In [41]:
#Training accuracy
y_true = y_train; print('y_test: ', y_train)
y_pred = np.random.randint(n_class, size = y_train.shape[0]); print('y_pred: ', y_pred)
acc = accuracy_score(y_true, y_pred);  print('training accuracy :', acc)

y_test:  [1 0 1 0 1 0 0 1]
y_pred:  [0 1 1 1 1 0 1 1]
training accuracy : 0.5


In [42]:
# Testing accuracy
y_true = y_test; print('y_test: ',y_test)
y_pred = np.random.randint(n_class, size=y_test.shape[0]); print('y_pred: ',y_pred)
acc = accuracy_score(y_true, y_pred); print('testing accuracy:', acc)

y_test:  [0 0 1 1]
y_pred:  [1 0 1 1]
testing accuracy: 0.75


In [44]:
from sklearn.linear_model import LinearRegression

In [46]:
# Create DATA
df = pd.DataFrame({"cigarettes": [0,10,20,30],
                     "CVD": [572,802,892,1025],
                    "lung": [14,105,208,355]});
print(df)

   cigarettes   CVD  lung
0           0   572    14
1          10   802   105
2          20   892   208
3          30  1025   355


In [47]:
# Setting input features x and target output y
X = np.array(df['cigarettes']).reshape(df['cigarettes'].shape[0],1); print(X)
y = np.array(df['CVD']); print(y)

[[ 0]
 [10]
 [20]
 [30]]
[ 572  802  892 1025]


In [48]:
# Fit model
reg = LinearRegression().fit(X, y)

In [49]:
# Print parameters
print(reg.coef_)
print(reg.intercept_)

[14.49]
605.4000000000001


In [50]:
# Print R-square
print(reg.score(X, y))

0.9630600857286361


In [51]:
# Make prediction
print(reg.predict(np.array([[250]])))

[4227.9]


In [60]:
#ต้อง pip install openpyxl ก่อน
df_path2 = 'ccpp.xlsx'
data = pd.read_excel(df_path2)
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [80]:
# Setting input features x and target output y
x = np.array(data[['AT','V','AP','RH']]); print(x)
y = np.array(data['PE']); print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [81]:
print('x_size :', x.shape)
print('y_size :', y.shape)

x_size : (9568, 4)
y_size : (9568,)


In [82]:
# Fit model
reg = LinearRegression().fit(x, y)

In [83]:
# Print parameters
print(reg.coef_)
print(reg.intercept_)

[-1.97751311 -0.23391642  0.06208294 -0.1580541 ]
454.60927431530985


In [84]:
# Print R-square
print(reg.score(x, y))

0.9286960898122536


In [85]:
# Make prediction
print(reg.predict(np.array([[17,52,1018,84]])))

[458.75178965]
